name: sample-workflow
on:
  push:
    branches: [master]
   
jobs:
  job1:
    runs-on: self-hosted
    steps:
    - name: checks-out your repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v2
    - name: use echo commnd
      run: echo "sample-workflow"
